# Generated by Django 5.2.3 on 2025-07-03 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_alter_vote_user_id'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
