# Generated by Django 5.2.3 on 2025-07-03 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_alter_author_name'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, max_length=150, unique=True, verbose_name='Имя автора'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='dislikes',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество дизлайков'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество лайков'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.TextField(max_length=1000, unique=True, verbose_name='Текст цитаты'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='weight',
            field=models.PositiveIntegerField(default=1, verbose_name='Вес цитаты'),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='Название источника'),
        ),
        migrations.AlterField(
            model_name='source',
            name='type',
            field=models.CharField(choices=[('book', 'Book'), ('movie', 'Movie'), ('series', 'TV Series'), ('song', 'Song'), ('public_speech', 'Public Speech')], verbose_name='Тип источника'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')])),
                ('quote_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.quote')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'unique_together': {('user_id', 'quote_id')},
            },
        ),
    ]
